server:
    port: 8080
    servlet:
        context-path: /FirmOrders
spring:
    application:
        name: FirmOrders
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the JAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: @spring.profiles.active@
    devtools:
        restart:
            enabled: false
    jmx:
        enabled: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,log4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        validationQuery: SELECT 1 FROM DUAL
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        show-sql: true

ehcache:
    file: ehcache.xml

httpheader:
    authorization: x-auth-token

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.firm.order.modules.*

poi:
    exceltemplatesPath: classpath:templates/excel-template

session:
    id: FIRMSESSIONID
    sessionTimeout: 7200000
    sessionTimeoutClean: 100000


